services:
  app:
    image: front-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    container_name: front-prod

  server:
    image: back-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    container_name: back-prod
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-phone-prod
    depends_on:
      - app
      - server